- hosts: localhost
  tasks:
    - name: Enable multi-user.target
      become: true
      command:
        argv:
          - systemctl
          - start
          - multi-user.target

    - name: Upload custom.yaml
      copy:
        src: res/custom.yaml
        dest: /home/candlepin/devel/candlepin/custom.yaml
        mode: preserve

    - name: Deploy Candlepin
      include_role:
        name: candlepin
      vars:
        cp_deploy_args: "-g -a -f -t -r -H"

    - name: Enable tomcat
      become: true
      service:
        name: tomcat
        enabled: true

    - name: Stop tomcat
      become: true
      service:
        name: tomcat
        state: stopped

    - name: Switch mode back to standalone
      become: true
      ansible.builtin.lineinfile:
        path: /etc/candlepin/candlepin.conf
        regexp: '^candlepin.standalone='
        line: candlepin.standalone=true

    - name: Kill gradle process
      command:
        argv:
          - pkill
          - "-e"
          - "-f"
          - gradle

    - name: Replace context.xml with working one
      become: true
      copy:
        src: res/context.xml
        dest: /var/lib/tomcat/webapps/ROOT/META-INF/context.xml
        mode: preserve
        owner: tomcat
        group: tomcat

    - name: Drop no more needed packages
      become: true
      dnf:
        name:
          - git-core
          - python3-psycopg2
          - createrepo_c
          - expect
          - gettext
          - hostname
          - man-db
          - python-unversioned-command
          - python3-libxml2
          - python3-requests
          - python3-six
          - policycoreutils-python-utils
          - procps
          - rpm-build
          - rpm-sign
          - unzip
          - "*-srpm-macros"
        state: absent
        autoremove: true

    - name: Cleanups
      become: true
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /home/candlepin/.java
        - /home/candlepin/devel/candlepin/build
        - /home/candlepin/devel/candlepin/buildSrc/build
        - /root/rpmbuild
        - /var/cache/dnf
        - /var/lib/tomcat/webapps/candlepin.war
        - /var/tmp/candlepin

    - name: Find .gradle directories
      find:
        paths: /home/candlepin
        patterns: .gradle
        hidden: true
        recurse: true
        file_type: directory
      register: gradle_dirs

    - name: Cleanups (.gradle directories)
      become: true
      file:
        path: "{{ item }}"
        state: absent
      loop:
        "{{ gradle_dirs.files | map(attribute='path') }}"

    - name: Cleanups (via shell)
      become: true
      shell: |
        set -euo pipefail
        rm -rf /usr/share/doc/* /usr/share/man/*
