# These tasks must be run as the candlepin user. main.yml imports this file with become_user set to
# {{ candlepin_user }}, but if these are included or imported anywhere else, that will likely need to
# be done there as well.
---
# Ensure Candlepin exists before attempting to run deployment
- name: "Deploy Candlepin"
  block:
    - name: "Execute deploy script"
      ansible.builtin.command:
        cmd: "env QUIET=1 {{ cp_deploy_script }} {{ cp_deploy_args }}"
        chdir: "{{ candlepin_home }}"
      changed_when: false
  environment:
    JAVA_HOME: "/usr/lib/jvm/java"
  vars:
    cp_deploy_script: "{{ candlepin_home }}/bin/deployment/deploy"
  tags:
    - candlepin
    - candlepin-deploy
