# These tasks must be run as the candlepin user. main.yml imports this file with become_user set to
# {{ candlepin_user }}, but if these are included or imported anywhere else, that will likely need to
# be done there as well.
---
- name: "Checkout Candlepin Repo"
  ansible.builtin.git:
    repo: "{{ cp_git_repo }}"
    version: "{{ cp_git_ref }}"
    dest: "{{ candlepin_home }}"
    force: true
    clone: true
    depth: 1
  when:
    - cp_git_checkout | bool
  tags:
    - candlepin
    - candlepin-setup
