---
- name: "Gather system facts"
  ansible.builtin.service_facts:
    # intentionally left empty
  tags:
    - always

- name: "Check supported OS"
  meta: end_play
  when:
    - ansible_distribution not in ["CentOS", "RedHat"]
    - ansible_distribution_major_version | int != 9
  tags:
    - always

- name: "Include EL9 tasks"
  ansible.builtin.include_tasks:
    file: el9/el9_tasks.yml
  when:
    - ansible_distribution in ["CentOS", "RedHat"]
    - ansible_distribution_major_version == "9"
  tags:
    - always

- name: "Include Candlepin debug tasks"
  ansible.builtin.import_tasks: common/cp_debugging.yml
  when:
    - cp_configure_debugging | bool

- name: "Include Candleping setup tasks"
  ansible.builtin.import_tasks: common/cp_setup.yml
  become: true
  become_user: "{{ candlepin_user }}"

- name: "Include Candlepin deploy tasks"
  ansible.builtin.import_tasks: common/cp_deploy.yml
  become: true
  become_user: "{{ candlepin_user }}"
  when:
    - cp_deploy | bool

- name: "Include user env tasks"
  ansible.builtin.import_tasks: common/user_env.yml
  become: true
  become_user: "{{ candlepin_user }}"
  when:
    - cp_configure_user_env | bool
