---
- name: "Update Tomcat configuration to use Alternatives-configured Java"
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/tomcat/tomcat.conf
    regexp: "JAVA_HOME="
    line: "JAVA_HOME=\"/usr/lib/jvm/java\""
  tags:
    - base_deps
    - candlepin
