name: image_build

on:
  workflow_dispatch:
    inputs:
      candlepin-ref:
        description: 'The reference of Candlepin to build'
        required: true
        default: 'main'
        type: string
      push-image:
        description: 'Push image'
        required: false
        default: true
        type: boolean
      update-latest:
        description: "Update 'latest' tag"
        required: false
        default: true
        type: boolean

env:
  IMAGE_NAME: candlepin-unofficial

jobs:
  image_build:
    name: "image_build"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Base setup
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            ansible-core \
            git-core \
            buildah \
            podman

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout candlepin.git
        uses: actions/checkout@v3
        with:
          repository: candlepin/candlepin
          path: candlepin.git
          ref: ${{ inputs.candlepin-ref }}

      - name: Install ansible bits
        run: |
          ansible-galaxy collection install -r requirements.yml

      - name: Initial build
        uses: redhat-actions/buildah-build@v2
        with:
          image: cp_base
          tags: build
          containerfiles: |
            ./Containerfile
          oci: true

      - name: Get container tag
        id: container-tag
        run: |
          export tag=$(echo ${{ inputs.candlepin-ref }} | sed 's/^candlepin-//g')
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Customization
        run: |
          set -euo pipefail
          podman run --name=candlepin --hostname=candlepin.local --publish=8443:8443 --publish=2222:22 --privileged --detach -t cp_base
          # wait for systemd to start in the container
          sleep 5
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory -v playbook.yml
          podman exec candlepin poweroff
          # wait for system shutdown
          sleep 5
          podman commit candlepin cp_custom

      - name: Build final image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ inputs.update-latest && format('{0} {1}', steps.container-tag.outputs.tag, 'latest') || steps.container-tag.outputs.tag }}
          base-image: cp_custom
          entrypoint: /sbin/init
          oci: true

      - name: List images
        run: |
          podman images

      - name: Push to the registry
        uses: redhat-actions/push-to-registry@v2
        if: inputs.push-image
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.actor }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
