name: image_build

on:
  workflow_dispatch:
    inputs:
      candlepin-ref:
        description: 'The reference of Candlepin to build'
        required: true
        default: 'main'
        type: string
      push-image:
        description: 'Push image'
        required: false
        default: true
        type: boolean
      update-latest:
        description: "Update 'latest' tag"
        required: false
        default: true
        type: boolean

env:
  IMAGE_NAME: candlepin-unofficial

jobs:
  image_build:
    name: "image_build"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Base setup
        run: |
          sudo apt-get update
          sudo apt-get -y dist-upgrade
          sudo apt-get -y install \
            ansible-core \
            git-core \
            buildah \
            podman

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout candlepin.git
        uses: actions/checkout@v3
        with:
          repository: candlepin/candlepin
          path: candlepin.git
          ref: ${{ inputs.candlepin-ref }}

      - name: Install ansible bits
        run: |
          ansible-galaxy collection install -r requirements.yml

      - name: Initial build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: cp_base
          tags: build
          containerfiles: |
            ./Containerfile
          oci: true

      - name: Get container tag
        id: container-tag
        run: |
          V=${{ inputs.candlepin-ref }} echo "::set-output name=tag::${INPUT,,}"
          export tag=$(echo ${{ inputs.candlepin-ref }} | sed 's/^candlepin-//g')
          echo ::set-output name=tag::$tag

      - name: Customization
        run: |
          set -euo pipefail
          podman run --name=candlepin --uts=host --publish=8443:8443 --publish=2222:22 --privileged --detach -t cp_base
          # wait for systemd to start in the container
          sleep 5
          podman exec candlepin systemctl start multi-user.target
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory -v playbook.yml
          podman exec candlepin systemctl enable tomcat
          podman exec candlepin dnf -y remove git-core python3-psycopg2 createrepo_c expect gettext hostname python3-libxml2 python3-requests rpm-build rpm-sign unzip
          podman exec candlepin poweroff
          # wait for system shutdown
          sleep 5
          podman commit candlepin ${{ env.IMAGE_NAME }}:${{ steps.container-tag.outputs.tag }}

      - name: Tag image as 'latest'
        if: inputs.update-latest
        run: |
          podman tag ${{ env.IMAGE_NAME }}:${{ steps.container-tag.outputs.tag }} ${{ env.IMAGE_NAME }}:latest

      - name: Push to the registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        if: ${{ inputs.push-image }}
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ inputs.update-latest && format('{0} {1}', steps.container-tag.outputs.tag, 'latest') || steps.container-tag.outputs.tag }}
          registry: ghcr.io/${{ github.actor }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
